# fraud_analysis.R
# TD Financial Crime Analytics — R Analytics Module
#
# Demonstrates R skills for Actuarial Analyst II (TD Insurance DAI team):
#   - Statistical anomaly detection on transaction data
#   - Time series trend analysis
#   - Risk tier distribution modelling
#   - ggplot2 visualisations for executive reporting
#   - Bilingual output (EN/FR) for Montreal DAI team
#
# Usage:
#   Rscript r/fraud_analysis.R
#   Rscript r/fraud_analysis.R --export    # save plots as PNG

# ── Dependencies ──────────────────────────────────────────────────────────────
required_packages <- c("ggplot2", "dplyr", "readr", "scales",
                       "lubridate", "tidyr", "patchwork")

for (pkg in required_packages) {
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cran.rstudio.com/", quiet = TRUE)
    library(pkg, character.only = TRUE)
  }
}

# ── Load data (generated by fraud_analytics.py --export) ──────────────────────
load_data <- function(data_dir = "data") {
  transactions <- read_csv(file.path(data_dir, "transactions.csv"),
                           col_types = cols(
                             transaction_date = col_date(),
                             amount_cad       = col_double(),
                             is_flagged       = col_logical()
                           ), show_col_types = FALSE)

  customers    <- read_csv(file.path(data_dir, "customers.csv"),
                           show_col_types = FALSE)

  risk_scores  <- read_csv(file.path(data_dir, "customer_risk_scores.csv"),
                           show_col_types = FALSE)

  list(transactions = transactions,
       customers    = customers,
       risk_scores  = risk_scores)
}

# ── 1. Statistical anomaly detection — IQR method ─────────────────────────────
#    Identifies transactions whose amounts are statistical outliers
#    relative to their transaction type. Core actuarial technique.

detect_amount_anomalies <- function(transactions) {
  transactions %>%
    group_by(transaction_type) %>%
    mutate(
      q1     = quantile(amount_cad, 0.25),
      q3     = quantile(amount_cad, 0.75),
      iqr    = q3 - q1,
      lower  = q1 - 1.5 * iqr,
      upper  = q3 + 3.0 * iqr,   # 3x IQR upper fence — financial data is right-skewed
      is_anomaly = amount_cad > upper | amount_cad < lower
    ) %>%
    ungroup() %>%
    filter(is_anomaly) %>%
    arrange(desc(amount_cad)) %>%
    select(transaction_id, customer_id, transaction_date,
           transaction_type, amount_cad, is_flagged, is_anomaly)
}

# ── 2. Monthly trend analysis ──────────────────────────────────────────────────
monthly_trends <- function(transactions) {
  transactions %>%
    mutate(month = floor_date(transaction_date, "month")) %>%
    group_by(month, transaction_type) %>%
    summarise(
      txn_count    = n(),
      total_amount = sum(amount_cad),
      flag_count   = sum(is_flagged),
      flag_rate    = mean(is_flagged),
      .groups      = "drop"
    )
}

# ── 3. Risk distribution modelling ────────────────────────────────────────────
risk_distribution <- function(risk_scores) {
  risk_scores %>%
    mutate(risk_tier = factor(risk_tier,
                              levels = c("Low", "Medium", "High", "Critical"))) %>%
    group_by(risk_tier, segment) %>%
    summarise(
      count        = n(),
      avg_score    = mean(composite_risk_score, na.rm = TRUE),
      avg_flagged  = mean(flagged_txns, na.rm = TRUE),
      .groups      = "drop"
    )
}

# ── 4. Structuring pattern analysis ───────────────────────────────────────────
#    Detects cash transactions clustered near the $10K reporting threshold
#    Mirrors PCMLTFA s.9 analysis

structuring_analysis <- function(transactions) {
  cash_types <- c("Cash Deposit", "Cash Withdrawal")

  transactions %>%
    filter(transaction_type %in% cash_types) %>%
    mutate(
      amount_band = case_when(
        amount_cad < 1000              ~ "< $1K",
        amount_cad < 5000              ~ "$1K–$5K",
        amount_cad < 9000              ~ "$5K–$9K",
        amount_cad < 9500              ~ "$9K–$9.5K",
        amount_cad < 10000             ~ "$9.5K–$9.999K ⚠",   # Structuring zone
        amount_cad == 10000            ~ "= $10K (Threshold)",
        amount_cad < 25000             ~ "$10K–$25K",
        TRUE                           ~ "> $25K"
      ),
      in_structuring_zone = amount_cad >= 9500 & amount_cad < 10000
    ) %>%
    group_by(amount_band) %>%
    summarise(
      count               = n(),
      total_amount        = sum(amount_cad),
      structuring_zone    = any(in_structuring_zone),
      .groups             = "drop"
    ) %>%
    arrange(desc(count))
}

# ── Visualisations ────────────────────────────────────────────────────────────

TD_PALETTE <- c(
  "Critical" = "#DC2626",
  "High"     = "#D97706",
  "Medium"   = "#CA8A04",
  "Low"      = "#16A34A",
  "flagged"  = "#EF4444",
  "clear"    = "#6B7280"
)

TD_THEME <- theme_minimal(base_size = 12) +
  theme(
    plot.title       = element_text(face = "bold", size = 14, colour = "#0A1628"),
    plot.subtitle    = element_text(colour = "#374151", size = 10),
    panel.grid.minor = element_blank(),
    axis.text        = element_text(colour = "#374151"),
    legend.position  = "bottom"
  )

# Plot 1: Transaction amount distribution by type
plot_amount_distribution <- function(transactions) {
  transactions %>%
    filter(amount_cad < quantile(amount_cad, 0.99)) %>%   # trim extreme outliers for vis
    ggplot(aes(x = amount_cad, fill = is_flagged)) +
    geom_histogram(bins = 50, alpha = 0.8, position = "stack") +
    scale_x_continuous(labels = dollar_format(prefix = "$", suffix = "")) +
    scale_fill_manual(values = c("FALSE" = "#6B7280", "TRUE" = "#DC2626"),
                      labels = c("Clear / Normal", "Flagged / Signalée")) +
    facet_wrap(~ transaction_type, scales = "free_y", ncol = 2) +
    labs(
      title    = "Transaction Amount Distribution by Type",
      subtitle = "Distribution des montants par type de transaction",
      x        = "Amount (CAD) / Montant (CAD)",
      y        = "Count / Nombre",
      fill     = "Status / Statut"
    ) +
    TD_THEME
}

# Plot 2: Monthly flagged transaction trend
plot_monthly_trend <- function(trends) {
  monthly_total <- trends %>%
    group_by(month) %>%
    summarise(total_flag_count = sum(flag_count),
              total_txns       = sum(txn_count),
              .groups          = "drop") %>%
    mutate(flag_rate = total_flag_count / total_txns)

  ggplot(monthly_total, aes(x = month)) +
    geom_col(aes(y = total_txns), fill = "#BFDBFE", alpha = 0.7) +
    geom_line(aes(y = total_flag_count * 10), colour = "#DC2626",
              linewidth = 1.2) +
    geom_point(aes(y = total_flag_count * 10), colour = "#DC2626", size = 2) +
    scale_x_date(date_labels = "%b %Y", date_breaks = "2 months") +
    scale_y_continuous(
      name     = "Total Transactions",
      sec.axis = sec_axis(~ . / 10, name = "Flagged Alerts / Alertes signalées")
    ) +
    labs(
      title    = "Monthly Transaction Volume vs. Flagged Alerts",
      subtitle = "Volume mensuel vs. alertes signalées (2024)"
    ) +
    TD_THEME +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

# Plot 3: Customer risk tier distribution by segment
plot_risk_distribution <- function(risk_dist) {
  ggplot(risk_dist, aes(x = segment, y = count, fill = risk_tier)) +
    geom_col(position = "fill", alpha = 0.9) +
    scale_fill_manual(values = TD_PALETTE[c("Low","Medium","High","Critical")]) +
    scale_y_continuous(labels = percent_format()) +
    coord_flip() +
    labs(
      title    = "Customer Risk Tier by Segment",
      subtitle = "Niveau de risque client par segment",
      x        = NULL,
      y        = "Proportion",
      fill     = "Risk Tier / Niveau de risque"
    ) +
    TD_THEME
}

# Plot 4: Structuring zone — cash transaction clustering
plot_structuring <- function(struct_data) {
  struct_data %>%
    mutate(
      amount_band = factor(amount_band, levels = unique(amount_band)),
      highlight   = structuring_zone
    ) %>%
    ggplot(aes(x = reorder(amount_band, count), y = count,
               fill = highlight)) +
    geom_col(alpha = 0.9) +
    scale_fill_manual(values = c("FALSE" = "#6B7280", "TRUE" = "#DC2626"),
                      labels = c("Normal range", "⚠ Structuring zone")) +
    coord_flip() +
    labs(
      title    = "Cash Transaction Amount Bands — Structuring Detection",
      subtitle = "Détection de fractionnement — $9,500–$9,999 CAD zone",
      x        = "Amount Band / Tranche de montant",
      y        = "Number of Transactions / Nombre de transactions",
      fill     = NULL
    ) +
    TD_THEME
}

# ── Summary report ────────────────────────────────────────────────────────────
print_summary <- function(data) {
  anomalies  <- detect_amount_anomalies(data$transactions)
  trends     <- monthly_trends(data$transactions)
  risk_dist  <- risk_distribution(data$risk_scores)

  cat("\n══════════════════════════════════════════════════════════\n")
  cat("  TD FINANCIAL CRIME ANALYTICS — R REPORT\n")
  cat("  Rapport analytique — criminalité financière TD\n")
  cat("══════════════════════════════════════════════════════════\n\n")

  cat("§1  STATISTICAL ANOMALIES (IQR method)\n")
  cat(sprintf("  %d transactions identified as statistical outliers\n",
              nrow(anomalies)))
  cat(sprintf("  Of which flagged by AML rules: %d (%.1f%%)\n",
              sum(anomalies$is_flagged),
              mean(anomalies$is_flagged) * 100))

  cat("\n§2  MONTHLY TREND SUMMARY\n")
  monthly_total <- trends %>%
    group_by(month) %>%
    summarise(txns = sum(txn_count), flags = sum(flag_count), .groups = "drop")
  cat(sprintf("  Peak flag month: %s (%d flags)\n",
              format(monthly_total$month[which.max(monthly_total$flags)], "%B %Y"),
              max(monthly_total$flags)))
  cat(sprintf("  Avg monthly flag rate: %.2f%%\n",
              mean(monthly_total$flags / monthly_total$txns) * 100))

  cat("\n§3  RISK TIER DISTRIBUTION\n")
  tier_summary <- data$risk_scores %>%
    count(risk_tier) %>%
    arrange(desc(n))
  print(tier_summary)

  cat("\n§4  STRUCTURING ZONE ANALYSIS\n")
  struct <- structuring_analysis(data$transactions)
  struct_zone <- struct %>% filter(structuring_zone)
  cat(sprintf("  Transactions in $9,500–$9,999 zone: %d\n",
              sum(struct_zone$count)))
  cat("  → Review against PCMLTFA s.9 structuring thresholds\n\n")
}

# ── Main ──────────────────────────────────────────────────────────────────────
main <- function() {
  args   <- commandArgs(trailingOnly = TRUE)
  export <- "--export" %in% args

  cat("Loading data from data/ directory...\n")
  cat("(Run 'python python/fraud_analytics.py --export' first if data/ is empty)\n\n")

  # Try to load real data; fall back to synthetic if not available
  data <- tryCatch(
    load_data("data"),
    error = function(e) {
      cat("⚠  data/ not found — generating synthetic data for demo\n")
      generate_synthetic_r()
    }
  )

  print_summary(data)

  # Generate plots
  cat("Generating visualisations...\n")
  plots <- list(
    p1 = plot_amount_distribution(data$transactions),
    p2 = plot_monthly_trend(monthly_trends(data$transactions)),
    p3 = plot_risk_distribution(risk_distribution(data$risk_scores)),
    p4 = plot_structuring(structuring_analysis(data$transactions))
  )

  if (export) {
    dir.create("plots", showWarnings = FALSE)
    ggsave("plots/01_amount_distribution.png", plots$p1,
           width = 12, height = 8, dpi = 150)
    ggsave("plots/02_monthly_trend.png",        plots$p2,
           width = 10, height = 6, dpi = 150)
    ggsave("plots/03_risk_distribution.png",    plots$p3,
           width = 8,  height = 5, dpi = 150)
    ggsave("plots/04_structuring_analysis.png", plots$p4,
           width = 10, height = 6, dpi = 150)
    cat("  Exported 4 plots to plots/\n")
  } else {
    print(plots$p2)   # Show monthly trend by default
  }
}

# ── Synthetic fallback (if Python data not yet generated) ─────────────────────
generate_synthetic_r <- function() {
  set.seed(42)
  n <- 500
  types <- c("Wire Transfer","Cash Deposit","Cash Withdrawal",
             "Interac e-Transfer","ACH")
  transactions <- data.frame(
    transaction_id   = sprintf("TXN%07d", 1:n),
    customer_id      = sprintf("C%05d",   sample(1:100, n, replace = TRUE)),
    transaction_date = as.Date("2024-01-01") + sample(0:364, n, replace = TRUE),
    transaction_type = sample(types, n, replace = TRUE),
    amount_cad       = rlnorm(n, meanlog = 7, sdlog = 1.3),
    is_flagged       = runif(n) < 0.08
  )
  risk_scores <- data.frame(
    customer_id           = sprintf("C%05d", 1:100),
    composite_risk_score  = runif(100, 5, 95),
    risk_tier             = sample(c("Low","Medium","High","Critical"),
                                   100, replace = TRUE,
                                   prob = c(0.5, 0.3, 0.15, 0.05)),
    flagged_txns          = sample(0:8, 100, replace = TRUE),
    segment               = sample(c("Retail","Small Business",
                                     "Commercial","Wealth"),
                                   100, replace = TRUE)
  )
  customers <- data.frame(
    customer_id = sprintf("C%05d", 1:100),
    segment     = risk_scores$segment
  )
  list(transactions = transactions,
       customers    = customers,
       risk_scores  = risk_scores)
}

main()
